* Sketch of paper
1. Lead with faster-fix and how it eg. speeds up transitive closure
   from O(n^2) to O(n).


* Theorems to put in paper
âŸ¦-âŸ§ : Datafun â†’ Poset is the standard semantics.
â¦ƒ-â¦„ : Datafun â†’ Î”Poset is the change semantics.
ğ“¤ : Î”Poset â†’ Poset is the forgetful functor.
For A : Î”Poset, ğ“¤A : Poset is the value poset
and Î”A : Poset is the change poset.

1. ğ“¤â¦ƒ-â¦„ = âŸ¦-âŸ§
2. Î”â¦ƒAâ¦„ = âŸ¦Î”AâŸ§
3. The logical relations proof.


** OLD, broken version
TODO: fix up this theorem todo list
1. UâŸ¦-âŸ§_Deriv = âŸ¦-âŸ§_Poset
2. â–¡ â‰… â– 
3. iso : âŸ¦AâŸ§_deriv â‰… âŸ¦AâŸ§_Ï†
4. Naturality, âŸ¦eâŸ§_deriv; iso = iso; âŸ¦eâŸ§_Ï†
5. Reading off âŸ¦-âŸ§_Ï† gives Ï†/Î´ translation, namely:
5a. âŸ¦Ï†eâŸ§_Poset = UâŸ¦eâŸ§_Ï† (= âŸ¦eâŸ§_Poset by Thm1).
5b. âŸ¦Î´eâŸ§_Poset is a derivative for (5a).

uh-oh, I think those last two don't even type-check!


* Roads not taken
There were a lot of choices we made that could have been made differently. I'd
like to have a section in the paper on them if there's room. In particular, we
could have, in no particular order:

1. Normalized first, then do seminaive transform only on first-order Datafun.

2. Used "change monoids" a la unpublished(?) Picallo & Michael PJ &c paper.

3. Tried to handle nested fixed points. This would involve 2nd and higher
   derivatives; could lazily compute them? Apply Paolo Giarrusso's thesis work?
   We didn't do this because it seems hard and Datalog can't do it.

4. Decided to include the derivative transform, not just the seminaive
   transform.

5. Augmented our target language with dependent types (to specify "zero change
   for a value") and quotients to try to make Î¦â–¡A more closely model the
   semantics.

6. Used two _separate_ comonads, one for discreteness, one for preventing nested
   fixed points. But then we'd have to think about how they interact!

7. Only stored zero-changes for _functions_, not for everything inside a boxed
   type. This seems related to letting Î¦(A_eq) = A_eq.

* Syntax sugar / conveniences

sets          â†’ downsets + discreteness
{eâ‚...eâ‚™}     â†’ {[eâ‚]} âˆ¨ ... âˆ¨ {[eâ‚™]}
discrete case â†’ splitsum
if-then-else  â†’ case & isEmpty
true,false    â†’ {[()]}, âŠ¥
when          â†’ for & sets of units
(fix x.e)     â†’ fix (box (Î»x.e))
eâ‚ = eâ‚‚       â†’ box eâ‚ = box eâ‚‚

explain why booleans-as-sets-of-units is helpful
(ie. use "when")
