[package]
name = "rust"
version = "0.1.0"
authors = ["Michael Arntzenius <daekharel@gmail.com>"]
edition = "2018"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.17.0"

[dependencies]
lazy_static = "*"
lalrpop-util = "0.17.0"
regex = "0.2.1"
unescape = "*"