let app x = `App x
let bool x = `Bool x
let box x = `Box x
let case x = `Case x
let fn x = `Fn x
let for_ x = `For x
let int x = `Int x
let lam v x = `Lam (v,x)
let let_ x = `Let x
let lub x = `Lub x
let name x = `Name x
let set x = `Set x
let str x = `Str x
let sum x = `Sum x
let tag n x = `Tag (n,x)
let the t x = `The (t,x)
let tuple x = `Tuple x
let unbox x = `Unbox x
